ansys/pyansys-units

AUTHORS.md
CODEOWNERS
CONTRIBUTORS.md
README.rst

Tidy up a few details after reviewing for package release.

Tidy up authoring / licensing details.

---

requirements/requirements_doc.txt
setup.py

fix pyunits dependencies and requirements

fix: deps and reqs

---

.github/workflows/ci_cd.yml

Private PY-PI upload step was missing.

Private PyPI upload changes before release

---

pyproject.toml
tests/test_metadata.py

Bump version 0.1

---

examples/00-pyunits/basic_usage.py
src/ansys/units/map.py
tests/test_map.py
tests/test_quantity.py

_maps_to_units does not deal with unit strings itself.
returns units in base SI currently. should this be changed?

map_to_units simplified.

---

src/ansys/units/__init__.py
src/ansys/units/unit_registry.py
tests/test_unit_registry.py

Unit registry attrs can be set once and not changed.

UnitRegistry attrs are immutable.

---

pyproject.toml
tests/test_metadata.py

Changed to follow PyFluent dev versioning.

Changed to 0.2.dev0

---

src/ansys/units/dimensions.py
src/ansys/units/unit.py
tests/test_dimensions.py
tests/test_systems.py
tests/test_unit.py

All test have been raised to 100 % coverage.

All Tests Updated

---

doc/source/user_guide/quantity.rst

Missed this comment from the last PR.
https://github.com/ansys/pyansys-units/pull/158#discussion_r1410727541

Quantity rst Update

---

doc/source/getting_started/index.rst
examples/00-pyunits/basic_usage.py
src/ansys/units/systems.py
src/ansys/units/unit.py
tests/test_systems.py

Unit System Naming Update

---

src/ansys/units/dimensions.py
src/ansys/units/map.py
src/ansys/units/quantity.py
src/ansys/units/systems.py
src/ansys/units/unit.py
src/ansys/units/unit_registry.py

Updated the docstring based on suggestions here: https://github.com/ansys/pyansys-units/pull/172/files#r1413695107

Quantity docstring updated.

---

src/ansys/units/cfg.yaml

Offset mentioned.
Should this be mentioned here? Is it only relevant at the base unit level?

Mention Offset in cfg.yaml

---

.github/workflows/ci_cd.yml

Added the missing style actions from: https://actions.docs.ansys.com/version/stable/style-actions/index.html
Added **commit style action**
Added **branch name style action**

feat: Added More Style Actions

---

pyproject.toml
tests/test_metadata.py

fix: Bump version 0.2.0

---

.github/workflows/ci_cd.yml
doc/.vale.ini
doc/source/getting_started/faq.rst
pyproject.toml

Resolved stable doc build deployment issue.

fix: stable doc build

---

.github/workflows/label.yml

Added write permission to page deployment.

build: dev doc fix

---

pyproject.toml
tests/test_metadata.py

refactor: Bump release 0.3.0

---

src/ansys/units/quantity.py
tests/test_quantity.py

- **make quantity immutable**
- test all aspects of immutability
- remove setter

feat: quantity is immutable

---

pyproject.toml
tests/test_metadata.py

refactor: Bump release 0.3.1

---

src/ansys/units/quantity.py
tests/test_quantity.py

Fix array indexing and iteration and remove conflicting tuple support.

feat: array iteration and indexing

---

doc/source/user_guide/quantity.rst

docs: updates to quantity docs

---

doc/source/api/unit.rst
doc/source/user_guide/quantity.rst
doc/source/user_guide/temperature.rst
doc/styles/Vocab/ANSYS/accept.txt
src/ansys/units/cfg.yaml
src/ansys/units/unit.py
tests/test_quantity.py
tests/test_unit.py

Closes https://github.com/ansys/pyansys-units/issues/255, https://github.com/ansys/pyansys-units/issues/256 and https://github.com/ansys/pyansys-units/issues/258
1. Updated temperature docs.
2. Added test for temperature addition.
3. Raise an exception for unimplemented units.
4. Added test to check unimplemented units.
5. Updated quantity doc.

docs: Remove temperature addition and disallow unimplemented unit construction

---

examples/00-pyunits/basic_usage.py
src/ansys/units/quantity_tables/bt_table.yaml
src/ansys/units/quantity_tables/cgs_table.yaml
src/ansys/units/quantity_tables/si_table.yaml
tests/test_quantity.py
tests/test_unit.py

Use CamelCase naming style in the YAML config.

feat: Update unit system config files

---

.github/workflows/ci_cd.yml
pyproject.toml

closes https://github.com/ansys/pyansys-units/issues/278
Fix for failing `Documentation Style Check`. 
https://github.com/ansys/pyansys-units/actions/runs/9073832568/job/24931558487?pr=275

fix: vale fix

---

AUTHORS
CONTRIBUTORS.md

fix: update CONTRIBUTORS.md file and authors

---

.github/workflows/ci_cd.yml
.pre-commit-config.yaml
CONTRIBUTORS.md
LICENSE
README.rst
doc/source/getting_started/installation.rst

closes https://github.com/ansys/pyansys-units/issues/308, https://github.com/ansys/pyansys-units/issues/310, https://github.com/ansys/pyansys-units/issues/311
1. Update CONTRIBUTORS.md
2. Support Python 3.13
3. Resolve dev doc deployment issue

chore: Maintenance tasks

---

pyproject.toml

fix: move quarto-cli deps and set open limits on main deps

---

.pre-commit-config.yaml
LICENSE
examples/00-pyunits/basic_usage.py
src/ansys/units/__init__.py
src/ansys/units/_constants.py
src/ansys/units/_version.py
src/ansys/units/base_dimensions.py
src/ansys/units/dimensions.py
src/ansys/units/quantity.py
src/ansys/units/systems.py
src/ansys/units/unit.py
src/ansys/units/unit_registry.py
tests/lib_compare/test_angle_units.py
tests/lib_compare/test_temperature_units.py
tests/lib_compare/util/__init__.py
tests/lib_compare/util/pint.py
tests/lib_compare/util/pyunit.py
tests/test_cfg.py
tests/test_dimensions.py
tests/test_metadata.py
tests/test_quantity.py
tests/test_systems.py
tests/test_unit.py
tests/test_unit_registry.py

closes https://github.com/ansys/pyansys-units/issues/329

chore: Update license file

---

doc/source/contributing.rst
doc/styles/config/vocabularies/ANSYS/accept.txt
pyproject.toml

closes https://github.com/ansys/pyansys-units/issues/334

docs: Update local doc build instructions

---

.github/workflows/ci_cd.yml
pyproject.toml

chore: Bump release to 0.4.0

---

doc/source/api/index.rst
doc/source/api/quantity_dimensions.rst
doc/source/api/variable_descriptor.rst
doc/source/user_guide/index.rst
doc/source/user_guide/quantity_dimensions.rst
doc/source/user_guide/variable_descriptor.rst
doc/styles/config/vocabularies/ANSYS/accept.txt
src/ansys/units/dimensions.py
src/ansys/units/variable_descriptor/variable_descriptor.py
tests/test_dimensions.py

Add docs for recently added modules: `quantity_dimensions`, `variable_descriptor`.

docs: var descriptors

---

pyproject.toml

build: Bump version to v0.5.0

---

pyproject.toml

build: Bump version to v0.6.dev0

---

src/ansys/units/quantity_dimensions.py

Clean up Materials Properties Quantities.

chore: mat-props

---

pyproject.toml

build: Bump version to v0.6.dev1

---

pyproject.toml
src/ansys/units/quantity_dimensions.py

build: Bump version to v0.5.1

---

pyproject.toml

ci: Bump version to v0.7.dev0

---

pyproject.toml

ci: Bump version to v0.7.0
